# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, coq-master, hook-tc ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.17'
        ocaml_version:
          - '4.09-flambda'
          - '4.13-flambda'
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: './coq-elpi.opam'
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        export: 'OPAMWITHTEST'
        install: |
          startGroup "Install dependencies"
            opam pin add -n -y -k path $PACKAGE $WORKDIR
            opam update -y
            opam install -y -j 2 $PACKAGE --deps-only
          endGroup
      env:
        OPAMWITHTEST: 'true'
